### ISSUE TITLE
including mocha.js in mocha-phantom script

### ISSUE THREAD

**Issue by bmark1111** [nathanboktae/mocha-phantomjs#213] opened 2015-10-14 17:35 UTC
I have the following mocha-phantomjs script:

var chai = require("vendor/chai");
var mocha = require('vendor/mocha');
mocha.ui('bdd');
mocha.reporter('html');
var expect  = chai.expect;

describe("Simple", function() {
	describe("constructor", function() {
		it("a simple test", function() {
			var test = 1 + 1;
			expect(test).to.equal(2);
			phantom.exit();
		});
	});
});

I keep getting the following error when running this from the command line:

mocha-phantomjs phantomtest.js 

mocha was not initialized before the page finished loading. Make sure to include mocha.js as a direct script and call `mocha.ui` or `mocha.setup`.

What am I doing wrong. 

Thanks for your help

**Comment by nathanboktae** [comment] 2015-10-14 17:37
You need to provide a reference to an HTML file. This is not node or
phantomjs code here.... Please read the readme carefully and see the
examples.

**Comment by bmark1111** [comment] 2015-10-14 17:45
Oh I see. I'm new to mocha-phantomjs so if you could just bear with me. When I run with my html test runner I get this error:

mocha-phantomjs v1.html

Error loading resource file:..............................  Details: Request for opening non-local file file:...............

**Comment by bmark1111** [comment] 2015-10-14 18:23
Read through all the examples and README. Sorry but still cant see an answer to my issue.

**Comment by nathanboktae** [comment] 2015-10-14 18:47
Dobyour tests run when you open `v1.html ` in a browser?

**Comment by bmark1111** [comment] 2015-10-14 19:52
yes they run fine

**Comment by nathanboktae** [comment] 2015-10-14 20:57
Resources errors don't necessarily mean your tests failed, and you'd see the same output in the console as you do in a browser. I can't really tell exactly from the information you provided.

**Comment by DexSinis** [comment] 2015-10-24 03:32
Likely due to external resource loading and timing, your tests require calling `window.initMochaPhantomJS()` before calling any mocha setup functions. See https://github.com/nathanboktae/mocha-phantomjs/issues/213

how can i fix this problem

**Comment by nathanboktae** [comment] 2015-10-24 04:16
Ah, the issue is actually nathanboktae/mocha-phantomjs-core#12, sorry about that.

But do what it says and call `window.initMochaPhantomJS()` before calling `mocha.setup` or other setup functions

```
window.initMochaPhantomJS && window.initMochaPhantomJS()
mocha.setup('bdd') // or whatever, mocha.ui('tdd'), mocha.slow(), etc etc...
```

**Comment by nathanboktae** [comment] 2015-10-24 04:18
closing since this is a clarification thread.

**Closed by nathanboktae** 2015-10-24 04:18 UTC
