### ISSUE TITLE
Upgrade PhantomJS

### ISSUE THREAD

**Issue by robertkowalski** [nathanboktae/mocha-phantomjs#233] opened 2016-04-13 12:46 UTC
Our CI fails because bitbucket does not serve PhantomJS properly.

Can you bump the PhantomJS version please, the team already has provided a fix: https://github.com/Medium/phantomjs/issues/506

```
> phantomjs@1.9.7-15 install /home/travis/build/robertkowalski/couchdb-fauxton/node_modules/mocha-phantomjs/node_modules/phantomjs
> node install.js
|\-PhantomJS detected, but wrong version 1.9.8 @ /usr/local/phantomjs/bin/phantomjs.
-js/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.7-linux-x86_64.tar.bz2
Receiving...
\Error requesting archive.
Status: 403
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": false
}
Response headers: {
  "x-amz-request-id": "FAF1F588BC11C2AC",
  "x-amz-id-2": "CFy1agk5W7iq2vyTLEuWl541mh3LuyZ9lgMuWAMhg79c5TyXJaqWtF5r8uKfuULNcWvwF5mh9Jc=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Wed, 13 Apr 2016 12:39:34 GMT",
  "server": "AmazonS3",
  "connection": "close"
}
Make sure your network and proxy settings are correct.
```

https://travis-ci.org/robertkowalski/couchdb-fauxton/builds/122771971

**Comment by yairEO** [comment] 2016-04-21 15:17
:+1:

**Comment by nathanboktae** [comment] 2016-04-25 15:26
Dupe of #231.

**Closed by nathanboktae** 2016-04-25 15:26 UTC
